-- 원본
CREATE TABLE MEMBERS(
		MEMBER_ID VARCHAR2(20),
		MEMBER_PWD VARCHAR2(20) NOT NULL,
		MEMBER_NAME CHAR(30),
		MEMBER_AGE NUMBER,
		MEMBER_EMAIL VARCHAR2(50),
		PRIMARY KEY (MEMBER_ID)
);

-- 조건
/*
1) MEMBER_ID 컬럼에 PRIMARY KEY 제약조건 설정.
2) MEMBER_PWD 컬럼에 NOT NULL 제약조건 설정.
3) MEMBER_NAME 컬럼에 가변 길이 문자열 30byte 설정.
 */
-- 수정
CREATE TABLE MEMBERS(
		MEMBER_ID VARCHAR2(20),
		MEMBER_PWD VARCHAR2(20) NOT NULL,
		MEMBER_NAME VARCHAR2(30),
		MEMBER_AGE NUMBER,
		MEMBER_EMAIL VARCHAR2(50),
		PRIMARY KEY (MEMBER_ID)
);

DROP TABLE MEMBERS;

SELECT * FROM MEMBERS;

INSERT INTO MEMBERS VALUES ('USER01', 'PASS01', '이영수','98',NULL);

--------------------------------------------------

-- 원본
CREATE TABLE BOARDS(
		BOARD_NO NUMBER PRIMARY KEY,
		BOARD_TITLE VARCHAR2(100),
		BOARD_CONTENT VARCHAR2(4000),
		BOARD_WRITER VARCHAR2(20) FOREIGN KEY MEMBERS(MEMBER_ID),
		BOARD_REG_DATE DATE DEFAULT '2023-03-22'
);

-- 조건
/*
1) BOARD_NO 컬럼에 PRIMARY KEY 제약조건 설정.
2) BOARD_WRITER 컬럼에 MEMERS 테이블의 MEMBER_ID를 참조하는 FOREIGN KEY 제약조건 설정.
3) BOARD_REG_DATE(작성일) 컬럼에 현재 시간으로 기본값 설정
 */
-- 수정
CREATE TABLE BOARDS(
		BOARD_NO NUMBER PRIMARY KEY,
		BOARD_TITLE VARCHAR2(100),
		BOARD_CONTENT VARCHAR2(4000),
		BOARD_WRITER VARCHAR2(20) REFERENCES MEMBERS,
		BOARD_REG_DATE DATE DEFAULT CURRENT_DATE
);

DROP TABLE BOARDS;

SELECT * FROM BOARDS;

INSERT INTO BOARDS (BOARD_NO,BOARD_TITLE,BOARD_CONTENT)
VALUES ('02','HELLO','WORLD!');

-- 컬럼레벨일 경우
-- 컬럼명 자료형(크기) [CONSTRAINT 이름] REFERENCES 참조할 테이블명 [(참조할컬럼)] [삭제룰]