CREATE TABLE SHOP_MEMBER (
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PW VARCHAR2(20) NOT NULL,
    PHONE CHAR(11) NOT NULL,
    GENDER CHAR(1)   	CHECK (GENDER IN ('M', 'F') )
);

DROP TABLE SHOP_MEMBER;

SELECT * FROM SHOP_MEMBER;

INSERT INTO SHOP_MEMBER(MEMBER_ID, MEMBER_PW, PHONE, GENDER)
--VALUES('user01','pass01','01011112222','M');
--VALUES('user02','pass02','01033334444','F');
--VALUES('user03','pass03','01055556666','M');
--VALUES('user04','pass04','01077778888','F');
;

   COMMENT ON COLUMN "SHOP_MEMBER"."MEMBER_ID" IS '아이디';
   COMMENT ON COLUMN "SHOP_MEMBER"."MEMBER_PW" IS '패스워드';
   COMMENT ON COLUMN "SHOP_MEMBER"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "SHOP_MEMBER"."GENDER" IS '성별';
  
  
COMMIT;