CREATE TABLE CUSTOMER(
	CUSTOMER_NO NUMBER PRIMARY KEY,
	CUSTOMER_NAME VARCHAR2(60) NOT NULL,
	CUSTOMER_TEL VARCHAR2(30) NOT NULL,
	CUSTOMER_ADDRESS VARCHAR2(200) NOT NULL
);

/***** [ 시퀀스 ] *****/

CREATE SEQUENCE SEQ_CUSTOMER_NO NOCACHE;

----------------------------------------------------------------------------------------------------

SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER
VALUES(SEQ_CUSTOMER_NO.NEXTVAL, '홍길동', '01012345678', '서울시 중구 남대문로');

ROLLBACK;

COMMIT;