-- JDBCExample5.java
-- TB_USER 테이블 생성
CREATE TABLE TB_USER (
		USER_NO 		NUMBER CONSTRAINT TB_USER_PK PRIMARY KEY,
		USER_ID 		VARCHAR2(30) NOT NULL,
		USER_PW 		VARCHAR2(30) NOT NULL,
		USER_NAME 	VARCHAR2(30) NOT NULL,
		ENROLL_DATE DATE DEFAULT CURRENT_DATE
)
;

COMMENT ON COLUMN TB_USER.USER_NO			IS '사용자 번호';
COMMENT ON COLUMN TB_USER.USER_ID			IS '사용자 아이디';
COMMENT ON COLUMN TB_USER.USER_PW			IS '사용자 비밀번호';
COMMENT ON COLUMN TB_USER.USER_NAME		IS '사용자 이름';
COMMENT ON COLUMN TB_USER.ENROLL_DATE IS '사용자 가입일';

-- USER_NO 컬럼에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO TB_USER
VALUES (SEQ_USER_NO.NEXTVAL, 'user01', 'pass01', '유저일', DEFAULT);
INSERT INTO TB_USER
VALUES (SEQ_USER_NO.NEXTVAL, 'user02', 'pass02', '유저이', DEFAULT);

SELECT * FROM TB_USER;

COMMIT;

DELETE FROM TB_USER;
DROP TABLE TB_USER;


-- 아이디, 비밀번호를 입력 받아
-- 아이디, 비밀번호가 일치하는 사용자(TB_USER)의
-- 이름을 수정
UPDATE TB_USER
SET USER_NAME = '유저일'
WHERE USER_ID = 'user01'
	AND USER_PW = 'pass01'
;
-- 아이디, 비밀번호 일치 	 ==> 수정 성공 (1)
-- 아이디, 비밀번호 불일치 ==> 수정 실패 (0)

SELECT * FROM TB_USER;
ROLLBACK;	-- 다른 트랜잭션이 형성이 되어있으면 java에서 오류가 날 수 있음