SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, SALARY, HIRE_DATE
FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY > 4000000 
;

-- 입력 받은 최소 급여 이상
-- 입력 받은 최대 급여 이하를 받는
-- 사원의 사번, 이름, 급여를
-- 급여 내림차순으로 조회
SELECT EMP_ID, EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 1000000 AND 3000000
ORDER BY SALARY DESC
;

-- 부서명을 입력 받아
-- 해당 부서에 근무하는 사원의
-- 사번, 이름, 부서명, 직급명을 
-- 직급코드 오름차순으로 조회
SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE, '없음'), JOB_NAME, JOB_CODE
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE DEPT_TITLE = '총무부'
ORDER BY JOB_CODE ASC
;

SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, SALARY, HIRE_DATE
                    FROM EMPLOYEE
                    ORDER BY EMP_ID ASC;
