CREATE TABLE TODO_LIST (
		TODO_TITLE VARCHAR2(20) NOT NULL,
		TODO_DETAIL VARCHAR2(1000),
		IS_COMPLETE CHAR(1) DEFAULT 'X' CHECK (IS_COMPLETE IN ('O', 'X') ) NOT NULL ,
		REGISTRATION_DATE DATE DEFAULT CURRENT_DATE
);

DROP TABLE TODO_LIST;

COMMENT ON COLUMN "TODO_LIST"."TODO_TITLE" IS '할 일 제목';
COMMENT ON COLUMN "TODO_LIST"."IS_COMPLETE" IS '완료 여부';
COMMENT ON COLUMN "TODO_LIST"."REGISTRATION_DATE" IS '등록 날짜';
